# Chapter 1: Iris

In [1]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()

print("Schlüssel von iris_dataset: \n{}".format(iris_dataset.keys()))

print("Ziele: {}".format(iris_dataset['target_names']))

print("Feature Names: {}".format(iris_dataset['feature_names']))

Schlüssel von iris_dataset: 
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])
Ziele: ['setosa' 'versicolor' 'virginica']
Feature Names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [3]:
print("Die ersten fuenf Zeilen: \n{}".format(iris_dataset['data'][:5]))

Die ersten fuenf Zeilen: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


## Trainings- und Testdaten

In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    iris_dataset['data'], iris_dataset['target'], random_state=0 )

In [ ]:
import pandas as pd

iris_dataframe = pd.DataFrame(X_train, columns=iris_dataset.feature_names)

# grr = pd.scatter_matrix(iris_dataframe, c=y_train, fig_size=(15,15), marker="o",
#                         hist_kwds={'bins': 20}, s=60, alpha=.8, cmap=mglearn.cm3)

In [5]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

In [6]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=1)

Eine Vorhersage treffen:

In [10]:
import numpy as np

X_new = np.array([[5, 2.9, 1, 0.2]])
print("New Shape: {}".format(X_new.shape))

New Shape: (1, 4)


In [11]:
prediction = knn.predict(X_new)

print("Vorhergesagter Name: {}".format(iris_dataset['target_names'][prediction]))

Vorhergesagter Name: ['setosa']


In [20]:
X_new2 = np.array([[4, 1.8, 2.4, 1.8]])
prediction2 = knn.predict(X_new2)
print("Vorhergesagter Name fuer 2: {}".format(iris_dataset['target_names'][prediction2]))

Vorhergesagter Name fuer 2: ['versicolor']


Evaluieren des Modells:

In [12]:
y_pred = knn.predict(X_test)
print("Vorhersagen fuer Testdatensatz:\n {}".format(y_pred))

Vorhersagen fuer Testdatensatz:
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [14]:
print("Genauigkeit auf den Testdaten: {:.3f}".format(np.mean(y_pred == y_test )))

Genauigkeit auf den Testdaten: 0.974
